name: Deploy ASP.NET to EC2

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet publish -c Release -o ./publish

    - name: Prepare SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./publish/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/tica-api

    - name: SSH into EC2 and restart application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        # Navegue até o diretório da aplicação no EC2 e execute comandos para reiniciar a aplicação
        cd /home/ubuntu/tica-api
        export ConnectionStrings__MysqlConnection=${{ secrets.CONNECTIONSTRINGS__MYSQLCONNECTION }}
        dotnet ExampleStore.dll
        EOF
